fixes
Signed-off-by: Raffaele Spazzoli <raffaele.spazzoli@gmail.com>

diff --git a/.github/workflows/push.yaml b/.github/workflows/push.yaml
--- a/.github/workflows/push.yaml
+++ b/.github/workflows/push.yaml
@@ -34,7 +34,7 @@ jobs:
         export TAG=${GITHUB_REF/refs\/tags\//}
         echo "BUNDLE_VERSION=${TAG:1}" >> $GITHUB_ENV
         export SEMVER_COMPLIANT=$(echo $BUNDLE_VERSION | egrep '^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-])(?:\.(?:0|[1-9]\d|\d*[a-zA-Z-][0-9a-zA-Z-]))))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$')
-        if [ SEMVER_COMPLIANT ]; then; else echo "invalid semver tag ${GITHUB_REF/refs\/tags\//}; exit 1; fi
+        if [ -z "$SEMVER_COMPLIANT" ]; then   echo "invalid semver tag ${GITHUB_REF/refs\/tags\//}"; exit 1; fi
 
     - name: Get the version for merge
       id: get_version2
