fix
Signed-off-by: Raffaele Spazzoli <raffaele.spazzoli@gmail.com>

diff --git a/.github/workflows/push.yaml b/.github/workflows/push.yaml
--- a/.github/workflows/push.yaml
+++ b/.github/workflows/push.yaml
@@ -33,8 +33,8 @@ jobs:
         echo "BUNDLE_IMAGE_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
         export TAG=${GITHUB_REF/refs\/tags\//}
         echo "BUNDLE_VERSION=${TAG:1}" >> $GITHUB_ENV
-        # export VALID_SEMVER=[[ $BUNDLEVERSION =~ ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$ ]] && echo "true" || echo "false" 
-        # if [ VALID_SEMVER != 'true' ]; then echo "invalid semver tag ${GITHUB_REF/refs\/tags\//}; exit 1; endif
+        export SEMVER_COMPLIANT=$(echo $BUNDLE_VERSION | egrep '^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-])(?:\.(?:0|[1-9]\d|\d*[a-zA-Z-][0-9a-zA-Z-]))))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$')
+        if [ SEMVER_COMPLIANT ]; then; else echo "invalid semver tag ${GITHUB_REF/refs\/tags\//}; exit 1; fi
 
     - name: Get the version for merge
       id: get_version2
